### PR TITLE
Make CredoContrib compatible with credo 1.x

### PR DESCRIPTION
**Pull request by Kitton**
Some breaking changes were done in credo 1.0

### CODE REVIEW

**Comment by Kitton** [comment]
not sure why travis-ci is broken. @xtian can you check this PR?

**Comment by xtian** [comment]
@Kitton Sorry, not sure what happened there. LGTM, thank you!!

**Comment by xtian** [comment]
I'm on a funky network atm so I can't do a release but I will do one when I get home.

**Comment by xtian** [comment]
0.1.1 published: https://hex.pm/packages/credo_contrib/0.1.1

Thanks again!

**Pull request merged**
